name: Code checks

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install numpy
        run: python -m pip install numpy
      - name: Run Test1
        run: python -m unittest test1.py
      - name: Run Test2
        run: python -m unittest test2.py
      - name: Run Test3
        run: python -m unittest test3.py
